#!/usr/bin/env bash
# Sync private modules from reelstack-modules repo into packages/modules/src/private/.
# Replaces manual copying. Uses rsync to mirror source, preserving .gitkeep in target.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SOURCE="/Users/pavvel/workspace/projects/reelstack-modules/src/"
TARGET="$REPO_ROOT/packages/modules/src/private/"

if [[ ! -d "$SOURCE" ]]; then
  echo "Error: source repo not found at $SOURCE" >&2
  exit 1
fi

echo "Syncing private modules..."
echo "  from: $SOURCE"
echo "  to:   $TARGET"

rsync -a --delete --itemize-changes \
  --exclude='.git' \
  --exclude='.gitkeep' \
  "$SOURCE" "$TARGET"

# Generate local Remotion entry with private compositions
LOCAL_ENTRY="$REPO_ROOT/apps/web/remotion-entry.local.ts"
cat > "$LOCAL_ENTRY" << 'EOF'
/**
 * Local Remotion entry point with private module compositions.
 * Auto-generated by scripts/sync-private-modules.sh — do not edit.
 * This file is .gitignored.
 */
import { registerRoot } from 'remotion';
import { RemotionRoot } from '@reelstack/remotion/compositions/Root';
import '@reelstack/modules/remotion';
import '../../packages/modules/src/private/remotion/index';
registerRoot(RemotionRoot);
EOF

echo "Done. Private modules synced + remotion-entry.local.ts generated."
